### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by ghost** [Byron/catchit-rs#5]
When i compile it in my terminal using **cargo build** every thing works fine but when i type **cargo run** i get a error for **line 195** in file directory **src/main.rs** . Is it a font issue? 

Screen shot here: [http://i.imgur.com/Szj4F6c.png]

using arch-linux desktop is gnome

**Comment by ghost** [comment]
After deleting the program i use git clone and rip the code on your page then when I follow the readme instructions i type `$ cargo run --release` and i get a series of errors
![screenshot from 2016-05-14 16-03-10](https://cloud.githubusercontent.com/assets/17482298/15270428/b6caf24c-19ed-11e6-8a83-b9121ddbba5b.png)
![screenshot from 2016-05-14 16-03-21](https://cloud.githubusercontent.com/assets/17482298/15270432/b6cf31cc-19ed-11e6-8369-96d645e318fd.png)
![screenshot from 2016-05-14 16-03-29](https://cloud.githubusercontent.com/assets/17482298/15270429/b6ce3376-19ed-11e6-92c6-41987ffb9fad.png)
![screenshot from 2016-05-14 16-03-37](https://cloud.githubusercontent.com/assets/17482298/15270431/b6ce78c2-19ed-11e6-8079-bd47ccb42e24.png)
![screenshot from 2016-05-14 16-03-44](https://cloud.githubusercontent.com/assets/17482298/15270430/b6ce534c-19ed-11e6-9eb2-726d16345adf.png)

**Comment by Byron** [comment]
I can reproduce the issue - it seems piston changed quite a bit in the meanwhile. Also I will spend some time to get it fixed, and provide more information (including `Cargo.lock`) to assure it remains possible to build this program.
